# -*- coding: utf-8 -*-
"""task 1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3EqirAOPCnxgi0_mRYiiuNoQZwoZhGp
"""

"""
AI Research Agent
Author: ChatGPT

This script implements a multi-agent AI research system:
1. Planner Agent
2. Researcher Agent (Tavily Search)
3. Writer Agent
4. Orchestrator to connect all agents
"""

# ----------------------------
# Imports
# ----------------------------
import os
from typing import List, Dict
from langchain_openai import ChatOpenAI
from langchain_community.tools.tavily_search import TavilySearchResults

# ----------------------------
# Planner Agent
# ----------------------------
class PlannerAgent:
    def __init__(self, llm):
        self.llm = llm

    def generate_sub_questions(self, topic: str) -> List[str]:
        prompt = f"""
        Break the following topic into 3 clear research questions:

        Topic: {topic}

        Return questions as bullet points.
        """
        response = self.llm.invoke(prompt).content
        return [q.strip("-• ") for q in response.split("\n") if q.strip()]

# ----------------------------
# Researcher Agent (Tavily)
# ----------------------------
class ResearcherAgent:
    def __init__(self):
        self.search_tool = TavilySearchResults(k=3)

    def search(self, questions: List[str]) -> Dict[str, str]:
        results = {}
        for q in questions:
            r = self.search_tool.run(q)
            text = "\n".join([doc["content"] for doc in r["results"]])
            results[q] = text
        return results

# ----------------------------
# Writer Agent
# ----------------------------
class WriterAgent:
    def __init__(self, llm):
        self.llm = llm

    def write_summary(self, research_data: Dict[str, str]) -> str:
        combined_text = "\n".join([f"{k}:\n{v}" for k, v in research_data.items()])
        prompt = f"""
        Create a structured research report based on the following data:

        {combined_text}

        Include:
        - Introduction
        - Insights for each sub-question
        - Conclusion
        """
        return self.llm.invoke(prompt).content

# ----------------------------
# Orchestrator
# ----------------------------
class AIResearchAgent:
    def __init__(self, openai_key: str):
        os.environ["OPENAI_API_KEY"] = openai_key
        self.llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)

        self.planner = PlannerAgent(self.llm)
        self.researcher = ResearcherAgent()
        self.writer = WriterAgent(self.llm)

    def run(self, topic: str) -> str:
        # Step 1: Planner
        sub_questions = self.planner.generate_sub_questions(topic)

        # Step 2: Researcher
        research_results = self.researcher.search(sub_questions)

        # Step 3: Writer
        final_report = self.writer.write_summary(research_results)
        return final_report

# ----------------------------
# Example Usage
# ----------------------------
if __name__ == "__main__":
    OPENAI_KEY = "YOUR_OPENAI_API_KEY"  # Replace with your OpenAI key

    agent = AIResearchAgent(OPENAI_KEY)

    topic = "Impact of Artificial Intelligence on Healthcare"
    report = agent.run(topic)

    print("\n=== FINAL RESEARCH REPORT ===\n")
    print(report)

pip install langchain-openai langchain-community tavily-python

"""
AI Research Agent - Error-free version
Author: ChatGPT

This script implements:
1. Planner Agent
2. Researcher Agent (using LLM for simplicity)
3. Writer Agent
4. Orchestrator to connect all agents
"""

import os
from typing import List, Dict
from openai import OpenAI

# ----------------------------
# Set your OpenAI API key
# ----------------------------
OPENAI_KEY = "YOUR_OPENAI_API_KEY"  # Replace with your key
os.environ["OPENAI_API_KEY"] = OPENAI_KEY
client = OpenAI(api_key=OPENAI_KEY)

pip install openai

python AI_Research_Agent_Simple.py